---
- name: Our first play
  hosts: planetexpress:!farnsworth

  tasks:

    - name: Install steam locomotive no ALL machines
      apt:
        name: sl
        state: present
      become: yes #run as superuser
